"""Change foreign key in messages_service db

Revision ID: 75aac88eb87b
Revises: d05b79cb4bf0
Create Date: 2025-10-06 22:29:18.699202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75aac88eb87b'
down_revision: Union[str, None] = 'd05b79cb4bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'files', 'chats', ['chat_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    # ### end Alembic commands ###
