"""Add interlocutor attribute for Chat

Revision ID: 0ab747ca555f
Revises: 5a074a526ba3
Create Date: 2025-10-13 10:36:07.194213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab747ca555f'
down_revision: Union[str, None] = '5a074a526ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('interlocutor', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'interlocutor')
    # ### end Alembic commands ###
